public with sharing class Bird {
    //propriedades e métodos get e set
    public String names 
    {
        get
        {
            return names;
        }
        set 
        {
            this.names = names;
        }
    }
    public String colors 
    {
        get 
        {
            return colors;
        }
        set
        {
            this.colors = colors;
        }
    }
    public Integer ages 
    {
        get 
        {
            return ages;
        }
        set 
        {
            this.ages = ages;
        }
    }
    public String breeds 
    {
        get
        {
            return breeds;
        }
        set 
        {
            this.breeds = breeds;
        }
    }
    public String photos 
    {
        get
        {
            return photos;
        }
        set 
        {
            this.photos = photos;
        }
    }
}